1 cat(miga alfa, umbral 4, tipo AC)
1 cat(miga alfa, umbral 4, tipo DS)
1 cat(miga beta, umbral 4, tipo DS)
4 ll(miga alfa)
1 ll(miga alfa)
1 ll(miga alfa)
1 ll(miga alfa)
91 ll(miga beta)
-90 ll(miga alfa)
21 ll(miga alfa)
;-15 ll(miga alfa)
1 ll(miga alfa)
1 ll(miga alfa)
1 ll(miga alfa)
;1 ll(miga alfa)
;1 ll(miga alfa)
;1 ll(miga alfa)
;1 ll(miga alfa)
70 ll(miga beta)
1 ll(miga beta)
1 ll(miga beta)
