0 e(clv zar, ad primero, gen_sec_alar -1, estado 0, sa 0)
0 e(clv zar, ad segundo, gen_sec_alar 1, estado 0, sa 0)
0 e(clv zar, ad tercero, gen_sec_alar 1, estado 0, sa 0)
;0 e(clv zar, data segundo, genera 1)
;0 e(clv zar, data tercero, genera 1)
;0 e(clv zor, data cuarto, genera 2)
;0 e(clv zar, data quinto, genera 0)
